-- Backup incremental generado el 2025-06-28 02:51:33.894645
-- Desde: mysql-bin.000003:157
-- Hasta: mysql-bin.000003:2108

TRUNCATE TABLE employees
DROP TABLE IF EXISTS `employees` /* generated by server */
CREATE TABLE `employees` (  `id` int NOT NULL AUTO_INCREMENT,  `name` varchar(100) NOT NULL,  `position` varchar(100) NOT NULL,  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
BEGIN
BEGIN