-- Backup incremental generado el 2025-06-28 03:24:45.498495
-- Desde: mysql-bin.000003:887
-- Hasta: mysql-bin.000003:3395

use `test_db`; TRUNCATE TABLE employees /* xid=65 */
use `test_db`; DROP TABLE IF EXISTS `employees` /* generated by server */ /* xid=77 */
use `test_db`; CREATE TABLE `employees` (  `id` int NOT NULL AUTO_INCREMENT,  `name` varchar(100) NOT NULL,  `position` varchar(100) NOT NULL,  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci /* xid=78 */
table_id: 91 (test_db.employees)
table_id: 91 flags: STMT_END_F
table_id: 91 (test_db.employees)
table_id: 91 flags: STMT_END_F
table_id: 91 (test_db.employees)
table_id: 91 flags: STMT_END_F
table_id: 91 (test_db.employees)
table_id: 91 flags: STMT_END_F
table_id: 91 (test_db.employees)
table_id: 91 flags: STMT_END_F
table_id: 91 (test_db.employees)
table_id: 91 flags: STMT_END_F
